# Generated by Django 5.0.6 on 2024-06-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('assigned_person', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=50)),
            ],
        ),
    ]
