# Generated by Django 5.1b1 on 2024-07-15 11:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits.')])),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('visible_to', models.ManyToManyField(blank=True, related_name='visible_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_partner', models.CharField(max_length=100)),
                ('products_discussed_partner', models.TextField()),
                ('products_discussed_company', models.TextField()),
                ('conclusion', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_records', to='website.record')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('ticket_type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200, null=True)),
                ('detailed_summary', models.TextField(null=True)),
                ('comments_history', models.TextField(null=True)),
                ('contract', models.CharField(max_length=200, null=True)),
                ('ticket_source', models.CharField(max_length=100, null=True)),
                ('resolution', models.TextField(null=True)),
                ('contact_name', models.CharField(max_length=200, null=True)),
                ('support_mode', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['assigned_to'], name='website_rec_assigne_e8c0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['created_at'], name='website_rec_created_d396e9_idx'),
        ),
    ]
