# Generated by Django 5.1b1 on 2024-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='remarks',
            field=models.CharField(max_length=200),
        ),
    ]
