# Generated by Django 5.1b1 on 2024-07-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrecord',
            name='record',
        ),
        migrations.AlterField(
            model_name='meetingrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingrecord',
            name='meeting_partner',
            field=models.CharField(max_length=255),
        ),
    ]
