# Generated by Django 5.1b1 on 2024-07-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
