# Generated by Django 5.1b1 on 2024-07-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_meetingrecord_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecord',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.record'),
        ),
        migrations.AlterField(
            model_name='meetingrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
