# Generated by Django 5.1b1 on 2024-07-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_meetingrecord_record_alter_meetingrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record'),
        ),
    ]
