# Generated by Django 5.1b1 on 2024-07-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_meetingrecord_follow_up_date_alter_meetingrecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
