# Generated by Django 5.0.8 on 2024-08-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_record_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='notification_sent',
        ),
    ]
