# Generated by Django 5.1b1 on 2024-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_record_social_media_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='classification',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('dead', 'Dead'), ('in_progress', 'In Progress')], default='unassigned', max_length=20),
        ),
    ]
