# Generated by Django 5.0.6 on 2024-07-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_record_assigned_person_record_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
